name: Heavy Tests

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'ci/**'
      - 'docs-generator/**'
      - '.editorconfig'
      - 'LICENSE.txt'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'ci/**'
      - 'docs-generator/**'
      - '.editorconfig'
      - 'LICENSE.txt'

jobs:
  JVM:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      #          cache: 'gradle'
      #          check-latest: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache test data
        uses: actions/cache@v4
        with:
          path: test-data
          key: test-data-${{ hashFiles('buildSrc/src/main/**/DefaultS3Deps.kt') }}

      - name: JVM Heavy Test
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: ./gradlew jvmHeavyTest --console=plain -Pci --no-daemon

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: heavy-test-report-jvm
          path: |
            **/build/**/test-results/**/* |
            **/build/**/reports/**/*

  JS-IR:
    runs-on: ubuntu-latest
    container:
      image: registry.jetbrains.team/p/ki/containers-ci/ci-corretto-17-firefox:1.0.1
      options: --user 1001

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache test data
        uses: actions/cache@v4
        with:
          path: test-data
          key: test-data-${{ hashFiles('buildSrc/src/main/**/DefaultS3Deps.kt') }}

      - name: JS IR Heavy Test
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: xvfb-run --auto-servernum ./gradlew jsHeavyTest --console=plain -Pci --no-daemon

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: heavy-test-report-js
          path: |
            **/build/**/test-results/**/* |
            **/build/**/reports/**/*
